name: CD

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: 🚀 Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get Latest Code
        uses: actions/checkout@v3

      - name: 📂 Sync Files to VPS
        uses: easingthemes/ssh-deploy@v4.0.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_SERVER_IP }}
          REMOTE_USER: "administador"
          REMOTE_PORT: 5780
          TARGET: "/home/administrador/backend/devaton-quita-edicion-grupo-uno-backend"
          SCRIPT: |
            git pull origin main
            npm install
